# Generated by Django 5.1.7 on 2025-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions_template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
